-- =====================================================================
-- TutorConnectSystem (TCS) - Initial schema
-- Engine: MySQL 8.0+  |  Charset: utf8mb4  |  Migration tool: Flyway
-- =====================================================================
-- Conventions:
--   * UUID  -> CHAR(36) (UUID v4 generated by the application layer)
--   * TIMESTAMP in the data dictionary -> DATETIME (avoids the MySQL
--     TIMESTAMP 2038 limit; CURRENT_TIMESTAMP defaults still apply)
--   * Enumerations enforced with CHECK constraints (MySQL 8.0.16+)
--   * Tables are created in FK-dependency order
--   * Some enum labels normalized to UPPER_SNAKE for consistency
--     ("Tutor Center" -> "TUTORCENTER", "Tutor Center_LICENSE" ->
--      "TUTORCENTER_LICENSE")
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------
-- Catalog / reference tables
-- ---------------------------------------------------------------------
CREATE TABLE province (
    province_id   CHAR(36)      NOT NULL,
    province_name VARCHAR(100)  NOT NULL,
    CONSTRAINT pk_province PRIMARY KEY (province_id),
    CONSTRAINT uq_province_name UNIQUE (province_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE location (
    location_id     CHAR(36)        NOT NULL,
    google_place_id VARCHAR(255)    NULL,
    address_line    VARCHAR(255)    NOT NULL,
    ward_name       VARCHAR(100)    NULL,
    district_name   VARCHAR(100)    NULL,
    province_id     CHAR(36)        NOT NULL,
    latitude        DECIMAL(10,8)   NULL,
    longitude       DECIMAL(11,8)   NULL,
    CONSTRAINT pk_location PRIMARY KEY (location_id),
    CONSTRAINT uq_location_google_place UNIQUE (google_place_id),
    CONSTRAINT fk_location_province FOREIGN KEY (province_id) REFERENCES province (province_id),
    CONSTRAINT chk_location_lat CHECK (latitude  IS NULL OR latitude  BETWEEN -90  AND 90),
    CONSTRAINT chk_location_lng CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE grade (
    grade_id   CHAR(36)     NOT NULL,
    grade_name VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_grade PRIMARY KEY (grade_id),
    CONSTRAINT uq_grade_name UNIQUE (grade_name),
    CONSTRAINT chk_grade_name CHECK (grade_name IN (
        'Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6',
        'Grade 7','Grade 8','Grade 9','Grade 10','Grade 11','Grade 12',
        'University'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE subject (
    subject_id   CHAR(36)      NOT NULL,
    subject_name VARCHAR(100)  NOT NULL,
    description  TEXT          NULL,
    CONSTRAINT pk_subject PRIMARY KEY (subject_id),
    CONSTRAINT uq_subject_name UNIQUE (subject_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE role (
    role_id     CHAR(36)     NOT NULL,
    role_name   VARCHAR(50)  NOT NULL,
    description TEXT         NULL,
    CONSTRAINT pk_role PRIMARY KEY (role_id),
    CONSTRAINT uq_role_name UNIQUE (role_name),
    CONSTRAINT chk_role_name CHECK (role_name IN ('ADMIN','CLIENT','TUTOR','TUTORCENTER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Identity / accounts
-- ---------------------------------------------------------------------
CREATE TABLE `user` (
    user_id       CHAR(36)      NOT NULL,
    email         VARCHAR(100)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    role_id       CHAR(36)      NOT NULL,
    status        VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login    DATETIME      NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role (role_id),
    CONSTRAINT chk_user_status CHECK (status IN ('PENDING','ACTIVE','BANNED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE client (
    client_id   CHAR(36)      NOT NULL,
    user_id     CHAR(36)      NOT NULL,
    full_name   VARCHAR(100)  NOT NULL,
    phone       VARCHAR(15)   NOT NULL,
    address     TEXT          NULL,
    location_id CHAR(36)      NULL,
    avatar      VARCHAR(255)  NULL,
    CONSTRAINT pk_client PRIMARY KEY (client_id),
    CONSTRAINT uq_client_user UNIQUE (user_id),
    CONSTRAINT fk_client_user     FOREIGN KEY (user_id)     REFERENCES `user` (user_id),
    CONSTRAINT fk_client_location FOREIGN KEY (location_id) REFERENCES location (location_id),
    CONSTRAINT chk_client_full_name CHECK (CHAR_LENGTH(full_name) >= 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tutor (
    tutor_id         CHAR(36)       NOT NULL,
    user_id          CHAR(36)       NOT NULL,
    full_name        VARCHAR(100)   NOT NULL,
    gender           VARCHAR(10)    NOT NULL,
    phone            VARCHAR(15)    NOT NULL,
    address          TEXT           NULL,
    location_id      CHAR(36)       NULL,
    experience_years INT            NOT NULL DEFAULT 0,
    bio              TEXT           NULL,
    hourly_rate      DECIMAL(12,2)  NOT NULL DEFAULT 0,
    rating_avg       DECIMAL(3,2)   NOT NULL DEFAULT 0,
    CONSTRAINT pk_tutor PRIMARY KEY (tutor_id),
    CONSTRAINT uq_tutor_user UNIQUE (user_id),
    CONSTRAINT fk_tutor_user     FOREIGN KEY (user_id)     REFERENCES `user` (user_id),
    CONSTRAINT fk_tutor_location FOREIGN KEY (location_id) REFERENCES location (location_id),
    CONSTRAINT chk_tutor_full_name  CHECK (CHAR_LENGTH(full_name) >= 2),
    CONSTRAINT chk_tutor_gender     CHECK (gender IN ('MALE','FEMALE','OTHER')),
    CONSTRAINT chk_tutor_experience CHECK (experience_years >= 0),
    CONSTRAINT chk_tutor_rate       CHECK (hourly_rate >= 0),
    CONSTRAINT chk_tutor_rating     CHECK (rating_avg BETWEEN 0.00 AND 5.00)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tutor_center (
    tutorcenter_id CHAR(36)      NOT NULL,
    user_id        CHAR(36)      NOT NULL,
    company_name   VARCHAR(150)  NOT NULL,
    license_no     VARCHAR(50)   NOT NULL,
    phone          VARCHAR(15)   NOT NULL,
    address        TEXT          NOT NULL,
    location_id    CHAR(36)      NULL,
    description    TEXT          NULL,
    CONSTRAINT pk_tutor_center PRIMARY KEY (tutorcenter_id),
    CONSTRAINT uq_tutor_center_user    UNIQUE (user_id),
    CONSTRAINT uq_tutor_center_license UNIQUE (license_no),
    CONSTRAINT fk_tutor_center_user     FOREIGN KEY (user_id)     REFERENCES `user` (user_id),
    CONSTRAINT fk_tutor_center_location FOREIGN KEY (location_id) REFERENCES location (location_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE platform_admin (
    admin_id  CHAR(36)      NOT NULL,
    user_id   CHAR(36)      NOT NULL,
    full_name VARCHAR(100)  NOT NULL,
    CONSTRAINT pk_platform_admin PRIMARY KEY (admin_id),
    CONSTRAINT uq_platform_admin_user UNIQUE (user_id),
    CONSTRAINT fk_platform_admin_user FOREIGN KEY (user_id) REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Tutor profile details
-- ---------------------------------------------------------------------
CREATE TABLE tutor_subject (
    tutor_subject_id  CHAR(36)      NOT NULL,
    tutor_id          CHAR(36)      NOT NULL,
    subject_id        CHAR(36)      NOT NULL,
    proficiency_level VARCHAR(50)   NULL,
    CONSTRAINT pk_tutor_subject PRIMARY KEY (tutor_subject_id),
    CONSTRAINT uq_tutor_subject UNIQUE (tutor_id, subject_id),
    CONSTRAINT fk_tutor_subject_tutor   FOREIGN KEY (tutor_id)   REFERENCES tutor (tutor_id),
    CONSTRAINT fk_tutor_subject_subject FOREIGN KEY (subject_id) REFERENCES subject (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE qualification (
    qualification_id CHAR(36)      NOT NULL,
    tutor_id         CHAR(36)      NOT NULL,
    title            VARCHAR(150)  NOT NULL,
    issuer           VARCHAR(150)  NOT NULL,
    issue_date       DATE          NULL,
    CONSTRAINT pk_qualification PRIMARY KEY (qualification_id),
    CONSTRAINT fk_qualification_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (tutor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Verification workflow
-- ---------------------------------------------------------------------
CREATE TABLE verification_request (
    verification_id   CHAR(36)     NOT NULL,
    user_id           CHAR(36)     NOT NULL,
    verification_type VARCHAR(50)  NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'Draft',
    submitted_at      DATETIME     NULL,
    reviewed_at       DATETIME     NULL,
    CONSTRAINT pk_verification_request PRIMARY KEY (verification_id),
    CONSTRAINT fk_verification_request_user FOREIGN KEY (user_id) REFERENCES `user` (user_id),
    CONSTRAINT chk_verification_type   CHECK (verification_type IN ('TUTOR_PROFILE','TUTORCENTER_LICENSE')),
    CONSTRAINT chk_verification_status CHECK (status IN ('Draft','Pending','Approved','Rejected')),
    CONSTRAINT chk_verification_reviewed CHECK (reviewed_at IS NULL OR submitted_at IS NULL OR reviewed_at >= submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE verification_document (
    document_id     CHAR(36)      NOT NULL,
    verification_id CHAR(36)      NOT NULL,
    file_url        VARCHAR(255)  NOT NULL,
    document_type   VARCHAR(50)   NOT NULL,
    CONSTRAINT pk_verification_document PRIMARY KEY (document_id),
    CONSTRAINT fk_verification_document_request FOREIGN KEY (verification_id) REFERENCES verification_request (verification_id),
    CONSTRAINT chk_document_type CHECK (document_type IN ('ID_CARD','DEGREE','CERTIFICATE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE verification_history (
    verification_history_id CHAR(36)     NOT NULL,
    verification_id         CHAR(36)     NOT NULL,
    old_status              VARCHAR(20)  NULL,
    new_status              VARCHAR(20)  NOT NULL,
    changed_by_user_id      CHAR(36)     NOT NULL,
    changed_at              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_verification_history PRIMARY KEY (verification_history_id),
    CONSTRAINT fk_verification_history_request FOREIGN KEY (verification_id)    REFERENCES verification_request (verification_id),
    CONSTRAINT fk_verification_history_user    FOREIGN KEY (changed_by_user_id) REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Marketplace: classes, applications, assignments, lessons
-- ---------------------------------------------------------------------
CREATE TABLE class (
    class_id       CHAR(36)       NOT NULL,
    creator_id     CHAR(36)       NOT NULL,
    subject_id     CHAR(36)       NOT NULL,
    title          VARCHAR(150)   NOT NULL,
    description    TEXT           NOT NULL,
    location_id    CHAR(36)       NULL,
    grade_id       CHAR(36)       NOT NULL,
    max_sessions   INT            NOT NULL DEFAULT 1,
    start_date     DATE           NOT NULL,
    end_date       DATE           NOT NULL,
    budget         DECIMAL(12,2)  NOT NULL DEFAULT 0,
    status         VARCHAR(20)    NOT NULL DEFAULT 'Draft',
    recurring_type VARCHAR(20)    NOT NULL DEFAULT 'ONCE',
    CONSTRAINT pk_class PRIMARY KEY (class_id),
    CONSTRAINT fk_class_creator  FOREIGN KEY (creator_id)  REFERENCES `user` (user_id),
    CONSTRAINT fk_class_subject  FOREIGN KEY (subject_id)  REFERENCES subject (subject_id),
    CONSTRAINT fk_class_location FOREIGN KEY (location_id) REFERENCES location (location_id),
    CONSTRAINT fk_class_grade    FOREIGN KEY (grade_id)    REFERENCES grade (grade_id),
    CONSTRAINT chk_class_max_sessions CHECK (max_sessions > 0),
    CONSTRAINT chk_class_budget       CHECK (budget > 0),
    CONSTRAINT chk_class_dates        CHECK (end_date > start_date),
    CONSTRAINT chk_class_status       CHECK (status IN ('Draft','Open','In Progress','Completed','Cancelled')),
    CONSTRAINT chk_class_recurring    CHECK (recurring_type IN ('ONCE','WEEKLY'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tutor_application (
    application_id CHAR(36)     NOT NULL,
    class_id       CHAR(36)     NOT NULL,
    tutor_id       CHAR(36)     NOT NULL,
    cover_letter   TEXT         NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'Submitted',
    applied_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tutor_application PRIMARY KEY (application_id),
    CONSTRAINT uq_tutor_application UNIQUE (class_id, tutor_id),
    CONSTRAINT fk_tutor_application_class FOREIGN KEY (class_id) REFERENCES class (class_id),
    CONSTRAINT fk_tutor_application_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (tutor_id),
    CONSTRAINT chk_application_status CHECK (status IN ('Submitted','Under Review','Accepted','Rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE application_status_history (
    application_history_id CHAR(36)     NOT NULL,
    application_id         CHAR(36)     NOT NULL,
    old_status             VARCHAR(20)  NULL,
    new_status             VARCHAR(20)  NOT NULL,
    changed_by_user_id     CHAR(36)     NOT NULL,
    changed_at             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_application_status_history PRIMARY KEY (application_history_id),
    CONSTRAINT fk_app_history_application FOREIGN KEY (application_id)     REFERENCES tutor_application (application_id),
    CONSTRAINT fk_app_history_user        FOREIGN KEY (changed_by_user_id) REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE class_assignment (
    assignment_id  CHAR(36)     NOT NULL,
    application_id  CHAR(36)     NOT NULL,
    assigned_date  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT pk_class_assignment PRIMARY KEY (assignment_id),
    CONSTRAINT uq_class_assignment_application UNIQUE (application_id),
    CONSTRAINT fk_class_assignment_application FOREIGN KEY (application_id) REFERENCES tutor_application (application_id),
    CONSTRAINT chk_assignment_status CHECK (status IN ('ACTIVE','TERMINATED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE lesson (
    lesson_id            CHAR(36)     NOT NULL,
    class_id             CHAR(36)     NOT NULL,
    lesson_date          DATE         NOT NULL,
    start_time           TIME         NOT NULL,
    end_time             TIME         NOT NULL,
    duration             INT          NOT NULL DEFAULT 0,
    status               VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    approved_by_user_id  CHAR(36)     NULL,
    CONSTRAINT pk_lesson PRIMARY KEY (lesson_id),
    CONSTRAINT fk_lesson_class    FOREIGN KEY (class_id)            REFERENCES class (class_id),
    CONSTRAINT fk_lesson_approver FOREIGN KEY (approved_by_user_id) REFERENCES `user` (user_id),
    CONSTRAINT chk_lesson_time     CHECK (end_time > start_time),
    CONSTRAINT chk_lesson_duration CHECK (duration > 0),
    CONSTRAINT chk_lesson_status   CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Finance: wallet, payments, escrow, refunds, payouts
-- ---------------------------------------------------------------------
CREATE TABLE wallet (
    wallet_id CHAR(36)       NOT NULL,
    user_id   CHAR(36)       NOT NULL,
    balance   DECIMAL(12,2)  NOT NULL DEFAULT 0,
    CONSTRAINT pk_wallet PRIMARY KEY (wallet_id),
    CONSTRAINT uq_wallet_user UNIQUE (user_id),
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES `user` (user_id),
    CONSTRAINT chk_wallet_balance CHECK (balance >= 0.00)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_method (
    payment_method_id CHAR(36)      NOT NULL,
    wallet_id         CHAR(36)      NOT NULL,
    type              VARCHAR(50)   NOT NULL,
    account_no        VARCHAR(50)   NOT NULL,
    bank_name         VARCHAR(100)  NULL,
    status            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT pk_payment_method PRIMARY KEY (payment_method_id),
    CONSTRAINT fk_payment_method_wallet FOREIGN KEY (wallet_id) REFERENCES wallet (wallet_id),
    CONSTRAINT chk_payment_method_type   CHECK (type IN ('BANK_ACCOUNT','VIETQR','PAYOS')),
    CONSTRAINT chk_payment_method_status CHECK (status IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment (
    payment_id        CHAR(36)       NOT NULL,
    payer_id          CHAR(36)       NOT NULL,
    amount            DECIMAL(12,2)  NOT NULL DEFAULT 0,
    payment_method_id CHAR(36)       NOT NULL,
    payment_status    VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_payment PRIMARY KEY (payment_id),
    CONSTRAINT fk_payment_payer  FOREIGN KEY (payer_id)          REFERENCES `user` (user_id),
    CONSTRAINT fk_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method (payment_method_id),
    CONSTRAINT chk_payment_amount CHECK (amount > 0.00),
    CONSTRAINT chk_payment_status CHECK (payment_status IN ('PENDING','SUCCESS','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_history (
    payment_history_id CHAR(36)     NOT NULL,
    payment_id         CHAR(36)     NOT NULL,
    old_status         VARCHAR(20)  NULL,
    new_status         VARCHAR(20)  NOT NULL,
    changed_by_user_id CHAR(36)     NULL,
    changed_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payment_history PRIMARY KEY (payment_history_id),
    CONSTRAINT fk_payment_history_payment FOREIGN KEY (payment_id)         REFERENCES payment (payment_id),
    CONSTRAINT fk_payment_history_user    FOREIGN KEY (changed_by_user_id) REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE escrow_transaction (
    escrow_id     CHAR(36)       NOT NULL,
    payment_id    CHAR(36)       NOT NULL,
    assignment_id CHAR(36)       NOT NULL,
    amount        DECIMAL(12,2)  NOT NULL DEFAULT 0,
    status        VARCHAR(20)    NOT NULL DEFAULT 'Pending',
    CONSTRAINT pk_escrow_transaction PRIMARY KEY (escrow_id),
    CONSTRAINT uq_escrow_payment UNIQUE (payment_id),
    CONSTRAINT fk_escrow_payment    FOREIGN KEY (payment_id)    REFERENCES payment (payment_id),
    CONSTRAINT fk_escrow_assignment FOREIGN KEY (assignment_id) REFERENCES class_assignment (assignment_id),
    CONSTRAINT chk_escrow_amount CHECK (amount > 0.00),
    CONSTRAINT chk_escrow_status CHECK (status IN ('Pending','Funded','Released','Refunded','On Hold'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE refund (
    refund_id CHAR(36)       NOT NULL,
    escrow_id CHAR(36)       NOT NULL,
    amount    DECIMAL(12,2)  NOT NULL DEFAULT 0,
    reason    TEXT           NOT NULL,
    status    VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_refund PRIMARY KEY (refund_id),
    CONSTRAINT fk_refund_escrow FOREIGN KEY (escrow_id) REFERENCES escrow_transaction (escrow_id),
    CONSTRAINT chk_refund_amount CHECK (amount > 0.00),
    CONSTRAINT chk_refund_status CHECK (status IN ('PENDING','APPROVED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE payment_release_request (
    request_id    CHAR(36)       NOT NULL,
    assignment_id CHAR(36)       NOT NULL,
    amount        DECIMAL(12,2)  NOT NULL DEFAULT 0,
    status        VARCHAR(20)    NOT NULL DEFAULT 'Pending',
    submitted_at  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payment_release_request PRIMARY KEY (request_id),
    CONSTRAINT fk_release_request_assignment FOREIGN KEY (assignment_id) REFERENCES class_assignment (assignment_id),
    CONSTRAINT chk_release_amount CHECK (amount > 0.00),
    CONSTRAINT chk_release_status CHECK (status IN ('Pending','Approved','Rejected','Paid'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Reputation, moderation & disputes
-- ---------------------------------------------------------------------
CREATE TABLE review (
    review_id     CHAR(36)  NOT NULL,
    reviewer_id   CHAR(36)  NOT NULL,
    reviewee_id   CHAR(36)  NOT NULL,
    assignment_id CHAR(36)  NULL,
    rating        INT       NOT NULL,
    comment       TEXT      NULL,
    CONSTRAINT pk_review PRIMARY KEY (review_id),
    CONSTRAINT uq_review_assignment UNIQUE (assignment_id),
    CONSTRAINT fk_review_reviewer   FOREIGN KEY (reviewer_id)   REFERENCES `user` (user_id),
    CONSTRAINT fk_review_reviewee   FOREIGN KEY (reviewee_id)   REFERENCES `user` (user_id),
    CONSTRAINT fk_review_assignment FOREIGN KEY (assignment_id) REFERENCES class_assignment (assignment_id),
    CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_review_self   CHECK (reviewer_id <> reviewee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE report (
    report_id   CHAR(36)      NOT NULL,
    reporter_id CHAR(36)      NOT NULL,
    target_type VARCHAR(50)   NOT NULL,
    target_id   CHAR(36)      NOT NULL,
    category    VARCHAR(50)   NOT NULL,
    description TEXT          NOT NULL,
    status      VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    CONSTRAINT pk_report PRIMARY KEY (report_id),
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_id) REFERENCES `user` (user_id),
    CONSTRAINT chk_report_target_type CHECK (target_type IN ('USER','CLASS','REVIEW')),
    CONSTRAINT chk_report_category    CHECK (category IN ('FRAUD','ABUSE','SPAM')),
    CONSTRAINT chk_report_status      CHECK (status IN ('PENDING','RESOLVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE dispute (
    dispute_id CHAR(36)      NOT NULL,
    report_id  CHAR(36)      NOT NULL,
    escrow_id  CHAR(36)      NOT NULL,
    resolution TEXT          NULL,
    status     VARCHAR(20)   NOT NULL DEFAULT 'Open',
    CONSTRAINT pk_dispute PRIMARY KEY (dispute_id),
    CONSTRAINT uq_dispute_report UNIQUE (report_id),
    CONSTRAINT fk_dispute_report FOREIGN KEY (report_id) REFERENCES report (report_id),
    CONSTRAINT fk_dispute_escrow FOREIGN KEY (escrow_id) REFERENCES escrow_transaction (escrow_id),
    CONSTRAINT chk_dispute_status CHECK (status IN ('Open','Under Investigation','Resolved','Waiting'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- Messaging & notifications
-- ---------------------------------------------------------------------
CREATE TABLE conversation (
    conversation_id CHAR(36)  NOT NULL,
    created_at      DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_conversation PRIMARY KEY (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE conversation_participant (
    conversation_participant_id CHAR(36)  NOT NULL,
    conversation_id             CHAR(36)  NOT NULL,
    user_id                     CHAR(36)  NOT NULL,
    CONSTRAINT pk_conversation_participant PRIMARY KEY (conversation_participant_id),
    CONSTRAINT uq_conversation_participant UNIQUE (conversation_id, user_id),
    CONSTRAINT fk_conv_participant_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (conversation_id),
    CONSTRAINT fk_conv_participant_user         FOREIGN KEY (user_id)         REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE message (
    message_id      CHAR(36)  NOT NULL,
    conversation_id CHAR(36)  NOT NULL,
    sender_id       CHAR(36)  NOT NULL,
    content         TEXT      NOT NULL,
    sent_at         DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_message PRIMARY KEY (message_id),
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (conversation_id),
    CONSTRAINT fk_message_sender       FOREIGN KEY (sender_id)       REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notification (
    notification_id CHAR(36)      NOT NULL,
    user_id         CHAR(36)      NOT NULL,
    type            VARCHAR(50)   NOT NULL,
    content         TEXT          NOT NULL,
    is_read         BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notification PRIMARY KEY (notification_id),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES `user` (user_id),
    CONSTRAINT chk_notification_type CHECK (type IN ('PAYMENT','APPLICATION','SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------
-- AI recommendation, knowledge base, audit, support, favorites
-- ---------------------------------------------------------------------
CREATE TABLE recommendation_log (
    recommendation_id CHAR(36)      NOT NULL,
    user_id           CHAR(36)      NOT NULL,
    tutor_id          CHAR(36)      NOT NULL,
    score             DECIMAL(5,2)  NOT NULL DEFAULT 0,
    generated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_recommendation_log PRIMARY KEY (recommendation_id),
    CONSTRAINT fk_recommendation_user  FOREIGN KEY (user_id)  REFERENCES `user` (user_id),
    CONSTRAINT fk_recommendation_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (tutor_id),
    CONSTRAINT chk_recommendation_score CHECK (score BETWEEN 0.00 AND 100.00)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE faq (
    faq_id   CHAR(36)      NOT NULL,
    question TEXT          NOT NULL,
    answer   TEXT          NOT NULL,
    category VARCHAR(50)   NULL,
    CONSTRAINT pk_faq PRIMARY KEY (faq_id),
    CONSTRAINT uq_faq_question UNIQUE (question(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audit_log (
    log_id      CHAR(36)      NOT NULL,
    user_id     CHAR(36)      NULL,
    action      VARCHAR(100)  NOT NULL,
    entity_name VARCHAR(100)  NOT NULL,
    entity_id   CHAR(36)      NOT NULL,
    timestamp   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (log_id),
    CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES `user` (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE support_ticket (
    ticket_id         CHAR(36)      NOT NULL,
    user_id           CHAR(36)      NOT NULL,
    category          VARCHAR(50)   NOT NULL,
    subject           VARCHAR(150)  NOT NULL,
    description       TEXT          NOT NULL,
    priority          VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM',
    status            VARCHAR(20)   NOT NULL DEFAULT 'OPEN',
    assigned_admin_id CHAR(36)      NULL,
    created_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_support_ticket PRIMARY KEY (ticket_id),
    CONSTRAINT fk_support_ticket_user  FOREIGN KEY (user_id)           REFERENCES `user` (user_id),
    CONSTRAINT fk_support_ticket_admin FOREIGN KEY (assigned_admin_id) REFERENCES platform_admin (admin_id),
    CONSTRAINT chk_ticket_category CHECK (category IN ('BUG_REPORT','INQUIRY')),
    CONSTRAINT chk_ticket_priority CHECK (priority IN ('LOW','MEDIUM','HIGH','URGENT')),
    CONSTRAINT chk_ticket_status   CHECK (status IN ('OPEN','IN_PROGRESS','CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE favorite_tutor (
    favorite_id CHAR(36)  NOT NULL,
    user_id     CHAR(36)  NOT NULL,
    tutor_id    CHAR(36)  NOT NULL,
    created_at  DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_favorite_tutor PRIMARY KEY (favorite_id),
    CONSTRAINT uq_favorite_tutor UNIQUE (user_id, tutor_id),
    CONSTRAINT fk_favorite_user  FOREIGN KEY (user_id)  REFERENCES `user` (user_id),
    CONSTRAINT fk_favorite_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (tutor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
