export const APP_ROUTES = {
  home: '/',
  findTutor: '/tim-gia-su',
  findClass: '/tim-lop',
  tutorProfile: '/gia-su/:tutorId',
  teaching: '/lich-day',
  login: '/login',
  register: '/register',
  identity: '/identity',
  profile: '/profile',
  finance: '/finance',
  catalog: '/catalog',
  verification: '/identity/verification',
  center: '/center',
  /** Trang công khai giới thiệu trung tâm + tin tuyển gia sư (khác /center là trang quản lý). */
  centers: '/centers',
  recruitment: '/recruitment',
  marketplace: '/marketplace',
  contract: '/contract',
  messaging: '/messaging',
  feedback: '/nhan-xet-gia-su',
  myReputation: '/nhan-xet-ve-toi',
  platform: '/platform',
  platformUsers: '/platform/users',
  platformVerifications: '/platform/verifications',
  platformReports: '/platform/reports',
  platformReviews: '/platform/reviews',
  platformProfile: '/platform/profile',
  forbidden: '/forbidden',
} as const;

export const tutorProfilePath = (tutorId: number | string) => `/gia-su/${tutorId}`;
