export const APP_ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  identity: '/identity',
  profile: '/profile',
  finance: '/finance',
  catalog: '/catalog',
  center: '/center',
  marketplace: '/marketplace',
  contract: '/contract',
  messaging: '/messaging',
  platform: '/platform',
  platformUsers: '/platform/users',
  platformVerifications: '/platform/verifications',
  platformReports: '/platform/reports',
  platformProfile: '/platform/profile',
  forbidden: '/forbidden',
} as const;
