spring.application.name=backend
# 1. ???ng d?n k?t n?i t?i MySQL và database b?n v?a t?o
spring.datasource.url=jdbc:mysql://localhost:3306/tutorconnectsystem?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. Tài kho?n & M?t kh?u MySQL trên máy c?a b?n (m?c ??nh th??ng là root)
spring.datasource.username=root
spring.datasource.password=12345

# 3. C?u hình Hibernate (T? ??ng t?o b?ng t? các file trong th? m?c 'model' c?a b?n)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true